/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef test_TYPES_H
#define test_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace tutorial {

typedef std::vector<int32_t>  int_list;

class Work;

class InvalidOperation;

typedef struct _Work__isset {
  _Work__isset() : n(false), k(false), m(false), comment(false) {}
  bool n :1;
  bool k :1;
  bool m :1;
  bool comment :1;
} _Work__isset;

class Work : public virtual ::apache::thrift::TBase {
 public:

  Work(const Work&);
  Work& operator=(const Work&);
  Work() : n(0), k(0), m(0), comment() {
  }

  virtual ~Work() throw();
  int32_t n;
  int32_t k;
  int32_t m;
  std::string comment;

  _Work__isset __isset;

  void __set_n(const int32_t val);

  void __set_k(const int32_t val);

  void __set_m(const int32_t val);

  void __set_comment(const std::string& val);

  bool operator == (const Work & rhs) const
  {
    if (!(n == rhs.n))
      return false;
    if (!(k == rhs.k))
      return false;
    if (!(m == rhs.m))
      return false;
    if (__isset.comment != rhs.__isset.comment)
      return false;
    else if (__isset.comment && !(comment == rhs.comment))
      return false;
    return true;
  }
  bool operator != (const Work &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Work & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Work &a, Work &b);

inline std::ostream& operator<<(std::ostream& out, const Work& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _InvalidOperation__isset {
  _InvalidOperation__isset() : para_num(false), why(false) {}
  bool para_num :1;
  bool why :1;
} _InvalidOperation__isset;

class InvalidOperation : public ::apache::thrift::TException {
 public:

  InvalidOperation(const InvalidOperation&);
  InvalidOperation& operator=(const InvalidOperation&);
  InvalidOperation() : para_num(0), why() {
  }

  virtual ~InvalidOperation() throw();
  int32_t para_num;
  std::string why;

  _InvalidOperation__isset __isset;

  void __set_para_num(const int32_t val);

  void __set_why(const std::string& val);

  bool operator == (const InvalidOperation & rhs) const
  {
    if (!(para_num == rhs.para_num))
      return false;
    if (!(why == rhs.why))
      return false;
    return true;
  }
  bool operator != (const InvalidOperation &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InvalidOperation & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
  mutable std::string thriftTExceptionMessageHolder_;
  const char* what() const throw();
};

void swap(InvalidOperation &a, InvalidOperation &b);

inline std::ostream& operator<<(std::ostream& out, const InvalidOperation& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
